// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqvjwfwtruoaafmcprnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxdmp3Znd0cnVvYWFmbWNwcm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NjMwNzAsImV4cCI6MjA2ODEzOTA3MH0.TWcOe0VrSD-830rHDRlV4fkA11Yln1daX-bfAwA39xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});